config/routes.rb
Rails.application.routes.draw do
  root 'static_people#home'

  get '/about', to: 'static_people#about'
  
  resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end

  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end


  private
  def people_params
    params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/controllers/static_people_controller.rb
class StaticPeopleController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_people_helper.rb
module StaticPeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |p| %>
  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :age %>
  <%= p.number_field :age %>

  <%= p.label :hair_color %>
  <%= p.text_field :hair_color %>

  <%= p.label :eye_color %>
  <%= p.text_field :eye_color %>

  <%= p.label :gender %>
  <%= p.text_field :gender %>

  <%= p.label :alive %>
  <%= p.check_box :alive, {}, true, false %>



  <%= p.submit %>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>

<% @people.each do |person| %>

<%= link_to 'Show Person', person_path(person) %>
<%= link_to 'Edit Person', edit_person_path(person) %>
<%= link_to 'Delete Person', person, method: :delete %><br/>
<% end %>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |p| %>
  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :age %>
  <%= p.number_field :age %>

  <%= p.label :hair_color %>
  <%= p.text_field :hair_color %>

  <%= p.label :eye_color %>
  <%= p.text_field :eye_color %>

  <%= p.label :gender %>
  <%= p.text_field :gender %>

  <%= p.label :alive %>
  <%= p.check_box :alive, {}, true, false %>



  <%= p.submit %>
<% end %>

app/views/people/show.html.erb
<h1>Person</h1>

<%= @person.name %><br/>
<%= @person.age %><br/>
<%= @person.hair_color %><br/>
<%= @person.eye_color %><br/>
<%= @person.gender %><br/>
<%= @person.alive %><br/>


<%= link_to 'Back', people_path %><br/>

app/views/static_people/about.html.erb
<h1>StaticPeople#about</h1>
<p>Find me in app/views/static_people/about.html.erb</p>

app/views/static_people/home.html.erb
<h1>StaticPeople#home</h1>
<p>Find me in app/views/static_people/home.html.erb</p>